<?php

namespace AppBundle\Repository;

/**
 * ImageConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
