<?php

namespace AppBundle\Repository;

/**
 * PointHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
