<?php

namespace AppBundle\Repository;

/**
 * SlackDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlackDomainRepository extends \Doctrine\ORM\EntityRepository
{
}
